### PR TITLE
Depend on MKL_jll

### LINKED ISSUE #18: Add dependency on MKL_jll.jl
That would make the package work automatically and make it easy to enable CI. MKL.jl overwrites OpenBLAS which currently can cause some issues when using other binary dependencies which require BLAS, e.g. Arpack so we might want to wait a bit. MKL.jl also causes a regression in REPL compile latency but hopefully, I'll be able to fix that soon.

We could probably add MKL.jl as a test dependency here as soon as it has been registered.

### PR DESCRIPTION
**Pull request by pablosanjose**
Closes #18

### CODE REVIEW

**Comment by pablosanjose** [comment]
Pinging @andreasnoack (also respect related PR #23) so we don't forget. This should be rather straightforward, I'd expect.

File: src/MKLSparse.jl [hunk 1]
```diff
@@ -1,7 +1,9 @@
 module MKLSparse
 
+using MKL_jll
+
 function __init__()
-    ccall((:MKL_Set_Interface_Layer, :libmkl_rt), Cint, (Cint,), Base.USE_BLAS64 ? 1 : 0)
+    ccall((:MKL_Set_Interface_Layer, libmkl_rt), Cint, (Cint,), Base.USE_BLAS64 ? 1 : 0)
```
Comment (KristofferC) [inline src/MKLSparse.jl:6]: I am a bit worried about this (for the future, not directly related to this PR). There has been ideas to use the 32-bit version for MKL with BLAS (https://github.com/JuliaComputing/MKL.jl/pull/35) but then all of a sudden, all your sparse matrix multiplications that use 64-bit integers would no longer hit the dispatch anymore...

Comment (KristofferC) [reply src/MKLSparse.jl:6]: One issue is that the interface layer can be changed at runtime but this package defines its overload for a compilation constant (`BlasInt`). This is because this package does type piracy (https://github.com/JuliaSparse/MKLSparse.jl/issues/24). It would be easier if there was a separate `MKLSparse.matmul` and then we can just query what interface is currently used and convert the matrix if needed.

Comment (pablosanjose) [reply src/MKLSparse.jl:6]: I actually think that would be far safer! I'd say we get this PR in shape and then address that change later.

**Comment by KristofferC** [comment]
Should update the README as well (mostly remove stuff about how to install MKL).
